name: Build & test
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Package build
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        pyver: [3.6, 3.7, 3.8, 3.9, 3.10]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          python -m pip install -U pip setuptools wheel build
      - run: |
          make package
      - uses: actions/upload-artifact@v2
        with:
          name: python-pkg-${{ matrix.os }}-py${{ matrix.pyver }}.whl
          path: dist/*.whl
  frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          make install
      - run: |
          make frontend_tests
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pyver: [3.6, 3.7, 3.8, 3.9, 3.10]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          python -m pip install -U pip setuptools wheel
      - run: |
          make install_test
      - run: |
          make backend_tests
